/**
 * Ingredient category lookup for grouping the grocery list.
 * Key = normalized name (lowercase, trim). Unmapped ingredients use "Uncategorized".
 */

export const CATEGORY_ORDER = [
  'Vegetables',
  'Fruits',
  'Spices',
  'Sauces',
  'Dairy & Eggs',
  'Meat & Seafood',
  'Pantry',
  'Beverages',
  'Uncategorized',
]

const INGREDIENT_TO_CATEGORY = {
  // Vegetables
  tomato: 'Vegetables',
  tomatoes: 'Vegetables',
  onion: 'Vegetables',
  onions: 'Vegetables',
  garlic: 'Vegetables',
  potato: 'Vegetables',
  potatoes: 'Vegetables',
  carrot: 'Vegetables',
  carrots: 'Vegetables',
  celery: 'Vegetables',
  'bell pepper': 'Vegetables',
  'bell peppers': 'Vegetables',
  broccoli: 'Vegetables',
  spinach: 'Vegetables',
  lettuce: 'Vegetables',
  cucumber: 'Vegetables',
  cucumbers: 'Vegetables',
  zucchini: 'Vegetables',
  mushroom: 'Vegetables',
  mushrooms: 'Vegetables',
  ginger: 'Vegetables',
  'green onion': 'Vegetables',
  'green onions': 'Vegetables',
  scallion: 'Vegetables',
  scallions: 'Vegetables',
  cabbage: 'Vegetables',
  kale: 'Vegetables',
  cauliflower: 'Vegetables',
  corn: 'Vegetables',
  peas: 'Vegetables',
  'green beans': 'Vegetables',
  asparagus: 'Vegetables',
  eggplant: 'Vegetables',
  leek: 'Vegetables',
  leeks: 'Vegetables',
  radish: 'Vegetables',
  radishes: 'Vegetables',
  squash: 'Vegetables',
  pumpkin: 'Vegetables',
  cilantro: 'Vegetables',
  parsley: 'Vegetables',
  mint: 'Vegetables',
  dill: 'Vegetables',
  chive: 'Vegetables',
  chives: 'Vegetables',
  coriander: 'Vegetables',
  'bok choy': 'Vegetables',
  'brussels sprouts': 'Vegetables',
  arugula: 'Vegetables',
  avocado: 'Vegetables',
  avocados: 'Vegetables',
  lime: 'Fruits',
  limes: 'Fruits',
  lemon: 'Fruits',
  lemons: 'Fruits',

  // Fruits
  apple: 'Fruits',
  apples: 'Fruits',
  banana: 'Fruits',
  bananas: 'Fruits',
  orange: 'Fruits',
  oranges: 'Fruits',
  strawberry: 'Fruits',
  strawberries: 'Fruits',
  blueberry: 'Fruits',
  blueberries: 'Fruits',
  raspberry: 'Fruits',
  raspberries: 'Fruits',
  blackberry: 'Fruits',
  blackberries: 'Fruits',
  mango: 'Fruits',
  mangoes: 'Fruits',
  pineapple: 'Fruits',
  watermelon: 'Fruits',
  grape: 'Fruits',
  grapes: 'Fruits',
  peach: 'Fruits',
  peaches: 'Fruits',
  pear: 'Fruits',
  pears: 'Fruits',
  plum: 'Fruits',
  plums: 'Fruits',
  cherry: 'Fruits',
  cherries: 'Fruits',
  coconut: 'Fruits',
  cranberry: 'Fruits',
  cranberries: 'Fruits',
  pomegranate: 'Fruits',
  kiwi: 'Fruits',
  melon: 'Fruits',
  papaya: 'Fruits',
  'passion fruit': 'Fruits',
  dates: 'Fruits',
  raisins: 'Fruits',
  'dried cranberries': 'Fruits',

  // Spices
  salt: 'Spices',
  pepper: 'Spices',
  'black pepper': 'Spices',
  paprika: 'Spices',
  cumin: 'Spices',
  turmeric: 'Spices',
  cinnamon: 'Spices',
  'ground cinnamon': 'Spices',
  'cinnamon stick': 'Spices',
  nutmeg: 'Spices',
  'chili powder': 'Spices',
  cayenne: 'Spices',
  'red pepper flakes': 'Spices',
  oregano: 'Spices',
  basil: 'Spices',
  thyme: 'Spices',
  rosemary: 'Spices',
  'bay leaf': 'Spices',
  'bay leaves': 'Spices',
  'garlic powder': 'Spices',
  'onion powder': 'Spices',
  'curry powder': 'Spices',
  coriander: 'Spices',
  cardamom: 'Spices',
  cloves: 'Spices',
  allspice: 'Spices',
  ginger: 'Spices',
  vanilla: 'Spices',
  'vanilla extract': 'Spices',
  mustard: 'Spices',
  'mustard seed': 'Spices',
  fennel: 'Spices',
  sage: 'Spices',
  'smoked paprika': 'Spices',
  'italian seasoning': 'Spices',
  'herbes de provence': 'Spices',
  'five spice': 'Spices',
  'star anise': 'Spices',
  saffron: 'Spices',
  sumac: 'Spices',

  // Sauces
  'soy sauce': 'Sauces',
  'light soy sauce': 'Sauces',
  'dark soy sauce': 'Sauces',
  'fish sauce': 'Sauces',
  'oyster sauce': 'Sauces',
  'hoisin sauce': 'Sauces',
  'shaoxing wine': 'Sauces',
  sriracha: 'Sauces',
  'hot sauce': 'Sauces',
  ketchup: 'Sauces',
  mustard: 'Sauces',
  mayonnaise: 'Sauces',
  'worcestershire sauce': 'Sauces',
  'barbecue sauce': 'Sauces',
  'teriyaki sauce': 'Sauces',
  tahini: 'Sauces',
  vinegar: 'Sauces',
  'rice vinegar': 'Sauces',
  'apple cider vinegar': 'Sauces',
  'balsamic vinegar': 'Sauces',
  'tomato paste': 'Sauces',
  'tomato sauce': 'Sauces',
  'lemon juice': 'Sauces',
  'lime juice': 'Sauces',
  salsa: 'Sauces',
  pesto: 'Sauces',
  'maple syrup': 'Sauces',

  // Dairy & Eggs
  eggs: 'Dairy & Eggs',
  milk: 'Dairy & Eggs',
  butter: 'Dairy & Eggs',
  cheese: 'Dairy & Eggs',
  cream: 'Dairy & Eggs',
  'heavy cream': 'Dairy & Eggs',
  'sour cream': 'Dairy & Eggs',
  yogurt: 'Dairy & Eggs',
  'greek yogurt': 'Dairy & Eggs',
  'cream cheese': 'Dairy & Eggs',
  parmesan: 'Dairy & Eggs',
  'parmesan cheese': 'Dairy & Eggs',
  cheddar: 'Dairy & Eggs',
  mozzarella: 'Dairy & Eggs',
  feta: 'Dairy & Eggs',
  ricotta: 'Dairy & Eggs',
  'cottage cheese': 'Dairy & Eggs',
  'half and half': 'Dairy & Eggs',

  // Meat & Seafood
  chicken: 'Meat & Seafood',
  'chicken breast': 'Meat & Seafood',
  'chicken thigh': 'Meat & Seafood',
  beef: 'Meat & Seafood',
  steak: 'Meat & Seafood',
  'ribeye steak': 'Meat & Seafood',
  'filet mignon': 'Meat & Seafood',
  't-bone steak': 'Meat & Seafood',
  'sirloin steak': 'Meat & Seafood',
  'rib steak': 'Meat & Seafood',
  'flank steak': 'Meat & Seafood',
  'hanger steak': 'Meat & Seafood',
  'tri-tip steak': 'Meat & Seafood',
  'flank steak': 'Meat & Seafood',
  'hanger steak': 'Meat & Seafood',
  'ground beef': 'Meat & Seafood',
  pork: 'Meat & Seafood',
  'pork belly': 'Meat & Seafood',
  'pork shoulder': 'Meat & Seafood',
  'pork ribs': 'Meat & Seafood',
  'pork loin': 'Meat & Seafood',
  'pork chop': 'Meat & Seafood',
  'pork tenderloin': 'Meat & Seafood',
  'pork roast': 'Meat & Seafood',
  bacon: 'Meat & Seafood',
  sausage: 'Meat & Seafood',
  salmon: 'Meat & Seafood',
  shrimp: 'Meat & Seafood',
  fish: 'Meat & Seafood',
  tuna: 'Meat & Seafood',
  cod: 'Meat & Seafood',
  tilapia: 'Meat & Seafood',
  crab: 'Meat & Seafood',
  lobster: 'Meat & Seafood',
  lamb: 'Meat & Seafood',
  turkey: 'Meat & Seafood',
  'ground turkey': 'Meat & Seafood',
  ham: 'Meat & Seafood',
  anchovy: 'Meat & Seafood',
  anchovies: 'Meat & Seafood',

  // Pantry
  'olive oil': 'Pantry',
  'vegetable oil': 'Pantry',
  'cooking oil': 'Pantry',
  'coconut oil': 'Pantry',
  'sesame oil': 'Pantry',
  'canola oil': 'Pantry',
  'peanut oil': 'Pantry',
  'neutral oil': 'Pantry',
  flour: 'Pantry',
  'all-purpose flour': 'Pantry',
  breadcrumbs: 'Pantry',
  sugar: 'Pantry',
  'brown sugar': 'Pantry',
  'rock sugar': 'Pantry',
  honey: 'Pantry',
  rice: 'Pantry',
  'basmati rice': 'Pantry',
  'long grain rice': 'Pantry',
  'short grain rice': 'Pantry',
  'brown rice': 'Pantry',
  'wild rice': 'Pantry',
  'jasmine rice': 'Pantry',
  'sticky rice': 'Pantry',
  pasta: 'Pantry',
  noodles: 'Pantry',
  beans: 'Pantry',
  'black beans': 'Pantry',
  'kidney beans': 'Pantry',
  chickpeas: 'Pantry',
  lentils: 'Pantry',
  oats: 'Pantry',
  oatmeal: 'Pantry',
  'peanut butter': 'Pantry',
  almonds: 'Pantry',
  walnuts: 'Pantry',
  peanuts: 'Pantry',
  cashews: 'Pantry',
  'coconut milk': 'Pantry',
  'canned tomatoes': 'Pantry',
  'chicken broth': 'Pantry',
  'vegetable broth': 'Pantry',
  'beef broth': 'Pantry',
  stock: 'Pantry',
  'baking powder': 'Pantry',
  'baking soda': 'Pantry',
  cornstarch: 'Pantry',
  yeast: 'Pantry',
  'cocoa powder': 'Pantry',
  chocolate: 'Pantry',
  bread: 'Pantry',
  tortilla: 'Pantry',
  tortillas: 'Pantry',
  crackers: 'Pantry',
  cereal: 'Pantry',
  quinoa: 'Pantry',
  couscous: 'Pantry',

  // Beverages
  water: 'Beverages',
  wine: 'Beverages',
  'red wine': 'Beverages',
  'white wine': 'Beverages',
  sake: 'Beverages',
  beer: 'Beverages',
  coffee: 'Beverages',
  tea: 'Beverages',
  juice: 'Beverages',
  'orange juice': 'Beverages',
  'apple juice': 'Beverages',
  'coconut water': 'Beverages',
  'coca cola': 'Beverages',
  'pepsi': 'Beverages',
  'sprite': 'Beverages',
  '7up': 'Beverages',
}

/** Categories that typically don't need a quantity (bought in bulk: spices, sauces). */
export const CATEGORIES_WITHOUT_QUANTITY = ['Spices', 'Sauces']

export function shouldShowQuantity(category) {
  return !CATEGORIES_WITHOUT_QUANTITY.includes(category)
}

// Normalize: lowercase, trim (caller typically passes mergedKey which is already normalized)
export function getCategory(normalizedName) {
  if (!normalizedName || typeof normalizedName !== 'string') return 'Uncategorized'
  const key = normalizedName.toLowerCase().trim()
  return INGREDIENT_TO_CATEGORY[key] ?? 'Uncategorized'
}

/** Known ingredient keys (normalized) for pantry search. */
export const KNOWN_INGREDIENTS = Object.keys(INGREDIENT_TO_CATEGORY)
